version: "2"

networks:
    internal:
        driver: bridge

services:

  # ---------------------------------
  # Database container
  # ---------------------------------

  db:
    extends:
      file: docker-compose-base.yml
      service: postgres-base
    networks:
      - internal

  # ---------------------------------
  # Gather container
  # ---------------------------------

  gather:
    extends:
      file: docker-compose-base.yml
      service: gather-base
    depends_on:
      - db
      - webpack
    networks:
      internal:
        aliases:
          - gather.local

  # ---------------------------------
  # Webpack container
  # ---------------------------------

  webpack:
    extends:
      file: docker-compose-base.yml
      service: webpack-base
    networks:
      - internal

  # ---------------------------------
  # NGINX container
  # ---------------------------------

  nginx:
    extends:
      file: docker-compose-base.yml
      service: nginx-base
    depends_on:
      - gather
      # - kernel
      # - odk
    networks:
      - internal
