db:
  image: "postgres:9.4"

importer:
  build: .
  volumes:
    - .:/code/
  command: bash /code/conf/entrypoint.sh  manage runserver 0.0.0.0:8001
  ports:
    - "8001:8001"
    - "8443:8443"
  links:
    - db
