language: python

python:
  - "2.7"

services:
  - docker

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install flake8

before_script:
  - flake8
  - docker-compose up -d db
  - docker-compose run core setuplocaldb

script:
  - docker-compose run core test_coverage

after_success:
  - git clone "https://${GH_USER}:${GH_TOKEN}@github.com/eHealthAfrica/beanstalk-deploy" .ebextensions

deploy:
  - provider: script
    script: ./scripts/deploy.sh "gather2-core-dev"
    skip_cleanup: true
    on:
      branch: master
