language: python
python:
  - "3.4"

services:
  - docker

cache:
  directories:
    - "$HOME/.cache/pip"

install:
  - pip install awscli ecs-deploy

script:
  - ./scripts/test_all.sh

after_script:
  - ./scripts/kill_all.sh

