language: python

python:
  - "3.4"

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.cache/pip

install:
    - pip install flake8 docker-compose

before_script:
  - flake8
  - docker-compose up -d db
  - docker-compose run core /code/gather2-core/entrypoint.sh sqlcreate
  - docker-compose run core /code/gather2-core/entrypoint.sh manage migrate
  - docker-compose run importer entrypoint.sh setupdb

script:
  - docker-compose run core /code/gather2-core/entrypoint.sh test_coverage
  - docker-compose run importer entrypoint.sh test_coverage
