language: python

addons:
  postgresql: "9.4"

python:
  - "3.4"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install flake8

before_script:
  - flake8
  - docker-compose run core /opt/gather2-core/entrypoint.sh sqlcreate

script:
  - docker-compose run core /opt/gather2-core/entrypoint.sh manage test core

