language: python

python:
  - "3.4"
  - "3.5"
  - "nightly"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install flake8
  - pip install -r requirements.txt

script:
  - virtualenv .
  - flake8 --exclude migrations --ignore E501,C901 ./gather2-core

