language: python

addons:
  postgresql: "9.5"

python:
  - "3.4"
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
    - docker-compose build web

install:
    - pip install flake8 docker-compose
    - pip install -r dev-requirements.txt

before_script:
    - docker-compose run init

script:
    - docker-compose run core

sudo: required

services:
    - docker
