language: python

addons:
  postgresql: "9.4"

python:
  - "3.4"
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install flake8
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - virtualenv .
  - flake8 --exclude migrations --ignore E501,C901 ./gather2-core
  - cd gather2-core && py.test core/tests.py

