language: python
python:
  - "3.4"

services:
  - docker

cache:
  directories:
    - "$HOME/.cache/pip"

script:
  - ./scripts/test_all.sh

after_script:
  - ./scripts/kill_all.sh

deploy:
  - provider: script
    script: "./scripts/release.sh"
    skip_cleanup: true
    on:
      branch: develop
