language: python

python:
  - "3.4"

cache:
  directories:
  - $HOME/.cache/pip

addons:
  postgresql: "9.4"

before_install:
  - docker-compose build init
  - docker-compose build core

install:
  - pip install flake8 docker-compose

before_script:
  - docker-compose run init

script:
  - flake8 --exclude migrations --ignore E501,C901 ./
  - docker-compose run core /opt/gather2-core-env/bin/python /opt/gather2-core/manage.py test --noinput

sudo: required

services:
  - docker
