language: python

addons:
  postgresql: "9.4"

python:
  - "3.4"

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.cache/pip

install:
    - pip install flake8 docker-compose

before_script:
  - flake8
  - docker-compose run core /opt/gather2-core/entrypoint.sh sqlcreate

script:
  - docker-compose run core /opt/gather2-core/entrypoint.sh test_coverage
