language: python

addons:
  postgresql: "9.4"

python:
  - "3.4"
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install flake8
  - pip install -r dev-requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - invoke check
  - invoke test -c Travis

