version: '2'
services:
    db:
        image: "postgres:9.5.2"

    couchdb:
        image: couchdb:1.6
        ports:
            - "5984:5984"
        volumes:
            # enable cors for mobile app in-browser development:
            - ./gather2-couchdb-sync/conf/couchdb/config-dev.ini:/usr/local/etc/couchdb/local.ini
        environment:
            COUCHDB_USER: admin
            COUCHDB_PASSWORD: secret

    core:
        build: gather2-core
        image: core
        environment:
            RDS_HOSTNAME: "db"
            RDS_USERNAME: "postgres"
            RDS_PASSWORD: ""
            RDS_PORT: ""
            RDS_DB_NAME: "gather2"
            STATIC_ROOT: "/var/www/static/"
        volumes:
            - ./gather2-core:/code
            - ./core_home:/root/
        hostname: gathercore-app
        ports:
            - "8000:8000"
        links:
            - db

    odk-importer:
        build: gather2-odk-importer
        image: odk-importer
        environment:
            RDS_HOSTNAME: "db"
            RDS_USERNAME: "postgres"
            RDS_PASSWORD: ""
            RDS_PORT: ""
            RDS_DB_NAME: "odk_importer"
            STATIC_ROOT: "/var/www/static/"
        volumes:
            - ./gather2-odk-importer:/code
            - ./importer_home:/root/
        ports:
            - "8443:8443"
        links:
            - core
            - db

    couchdb-sync:
        build: gather2-couchdb-sync
        image: couchdb-sync
        environment: &couchdb_environment
            RDS_HOSTNAME: "db"
            RDS_USERNAME: "postgres"
            RDS_PASSWORD: ""
            RDS_PORT: ""
            RDS_DB_NAME: "couchdb_sync"
            STATIC_ROOT: "/var/www/static/"
            COUCHDB_URL: "http://couchdb:5984"
            COUCHDB_USER: admin
            COUCHDB_PASSWORD: secret
            GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
            GATHER_CORE_URL: "http://core:8000"
            GATHER_CORE_TOKEN: "${GATHER_CORE_TOKEN}"
            REDIS_HOST: 'redis'
            REDIS_PORT: '6379'
            REDIS_DB: 0
            REDIS_PASSWORD: ''
        volumes:
            - ./gather2-couchdb-sync:/code
            - ./couchdb_home:/root/
        ports:
            - "8666:8666"
        links:
            - couchdb
            - db
    redis:
        image: redis:3.2

    couchdb-sync-rq:
        image: couchdb-sync
        links:
            - couchdb
            - core
            - db
            - redis
        environment: *couchdb_environment
        command: start_rq_dev
        volumes:
            - ./gather2-couchdb-sync:/code

    nginx:
         build: gather2-couchdb-sync/nginx
         volumes:
             - ./gather2-couchdb-sync/nginx/conf/local.conf:/etc/nginx/conf.d/default.conf
         links:
             - couchdb
             - couchdb-sync
         ports:
             - "8667:8667"
