version: "2"

services:
    db:
        image: postgres:9.5.2
        environment:
            RDS_HOSTNAME: "db"
            RDS_PASSWORD: ""
            RDS_PORT: "5432"
            RDS_USERNAME: "postgres"

    couchdb:
        image: couchdb:1.6
        environment:
            COUCHDB_USER: admin
            COUCHDB_PASSWORD: secret
        volumes:
            # enable cors for mobile app in-browser development:
            - ./gather2-couchdb-sync/conf/couchdb/config-dev.ini:/usr/local/etc/couchdb/local.ini
        ports:
            - "5984:5984"

    redis:
        image: redis:3.2-alpine


    # ---------------------------------
    # Gather2 Core container
    # ---------------------------------

    core:
        build: gather2-core
        image: core
        hostname: gathercore-app
        environment:
            RDS_DB_NAME: "gather2"
            RDS_HOSTNAME: "db"
            RDS_PASSWORD: ""
            RDS_PORT: "5432"
            RDS_USERNAME: "postgres"
            WEB_SERVER_PORT: "8000"
        volumes:
            - ./gather2-core:/code
            - ./core_home:/root/
        depends_on:
            - db
        ports:
            - "8000:8000"
        command: start_dev


    # ---------------------------------
    # ODK Adapter container
    # ---------------------------------

    odk-importer:
        build: gather2-odk-importer
        image: odk-importer
        environment:
            GATHER_CORE_TOKEN: "${GATHER_CORE_TOKEN}"
            GATHER_CORE_URL: "http://core:8000"
            RDS_DB_NAME: "odk_importer"
            RDS_HOSTNAME: "db"
            RDS_PASSWORD: ""
            RDS_PORT: "5432"
            RDS_USERNAME: "postgres"
            WEB_SERVER_PORT: "8443"
        volumes:
            - ./gather2-odk-importer:/code
            - ./importer_home:/root/
        depends_on:
            - core
            - db
        ports:
            - "8443:8443"
        command: start_dev


    # ---------------------------------
    # Mobile Sync containers
    # ---------------------------------

    couchdb-sync:
        build: gather2-couchdb-sync
        image: couchdb-sync
        environment: &couchdb_environment
            COUCHDB_PASSWORD: secret
            COUCHDB_URL: "http://couchdb:5984"
            COUCHDB_USER: admin
            GATHER_CORE_TOKEN: "${GATHER_CORE_TOKEN}"
            GATHER_CORE_URL: "http://core:8000"
            GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
            RDS_DB_NAME: "couchdb_sync"
            RDS_HOSTNAME: "db"
            RDS_PASSWORD: ""
            RDS_PORT: "5432"
            RDS_USERNAME: "postgres"
            REDIS_DB: 0
            REDIS_HOST: "redis"
            REDIS_PASSWORD: ""
            REDIS_PORT: "6379"
            WEB_SERVER_PORT: "8666"
        volumes:
            - ./gather2-couchdb-sync:/code
            - ./couchdb_home:/root/
        depends_on:
            - core
            - couchdb
            - db
            - redis
        ports:
            - "8666:8666"
        command: start_dev

    couchdb-sync-rq:
        image: couchdb-sync
        environment: *couchdb_environment
        volumes:
            - ./gather2-couchdb-sync:/code
        depends_on:
            - couchdb
            - core
            - db
            - redis
        command: start_rq_dev
