db:
  image: "postgres:9.4"

core:
  build: gather2-core/.
  environment:
      RDS_HOSTNAME: "db"
      RDS_USERNAME: "postgres"
      RDS_PASSWORD: ""
      RDS_PORT: ""
      RDS_DB_NAME: "connectdb"
      STATIC_ROOT: "/var/www/static/"
  volumes:
    - .:/code/
  command: manage runserver 0.0.0.0:8000
  ports:
    - "5000:5000"
    - "8000:8000"
  links:
    - db

importer:
  build: gather2-odk-importer/.
  volumes:
      - ./gather2-odk-importer/:/code
  environment:
      DJANGO_SETTINGS_MODULE: "importer.settings"
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "7000:8000"
  links:
    - db
    - core
