branch-defaults:
  default:
    environment: gather2-core-stage
  master:
    environment: gather2-core-stage
global:
  application_name: gather2-core
  default_ec2_keyname: aws-deploy
  default_platform: 64bit Amazon Linux 2015.09 v2.0.6 running Multi-container Docker
    1.7.1 (Generic)
  default_region: eu-central-1
  profile: null
  sc: git
deploy:
    artifact: gather2-core/conf/deploy.zip
